name: trigger workflow

on:
  workflow_dispatch:

jobs:
  triggerinferencejob:
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2
      
  job2:
    if: always()
    needs: triggerinferencejob
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2

    - name: somestep
      run: echo Running job2
      
  job3:
    if: always()
    needs: job2
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2

    - name: training_job3
      run: echo dummy run job 3
  
  sendmail:
    runs-on: ubuntu-latest
    if: always()
    needs: [triggerinferencejob, job2, job3]

    steps:
    - uses: technote-space/workflow-conclusion-action@v2

    - name: check workflow
      run: echo ${{ env.WORKFLOW_CONCLUSION }}

    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: test subject
        # email body as text
        body: The result of workflow is ${{ env.WORKFLOW_CONCLUSION }} 
        # comma-separated string, send email to
        to: darrshan13897.da@gmail.com
        # from email name
        from: Darshan
