name: trigger inference

on:
  workflow_dispatch:

jobs:
  inferencejob:
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2

    - name: Install requirements
      run: |
          echo "Installing dependencies and caching them."
          pip install -r requirements.txt

    - name: Test env for python
      env:
        access_token: ${{ secrets.ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: AKIAWJXAAGDYEM6T7RK5
        AWS_SECRET_ACCESS_KEY: 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
        AWS_DEFAULT_REGION: 'us-east-1'
      run: python main.py
    
