on:
  workflow_dispatch:

jobs:
  triggerinferencejob:
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2
      
  job2:
    if: always()
    needs: triggerinferencejob
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2

    - name: training_job2
      run: exit 1
      continue-on-error: true

    - name: somestep
      run: echo ${{ job.status }} > job2_status.txt
      
  job3:
    if: always()
    needs: job2
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2

    - name: training_job3
      run: dummy run
      continue-on-error: true

    - name: somestep
      run: echo ${{ job.status }} > job3_status.txt

  - name: Send mail
    if: always()
    needs: [triggerinferencejob, job2, job3]
    uses: dawidd6/action-send-mail@v2
    with:
      # mail server settings
      server_address: smtp.gmail.com
      server_port: 465
      # user credentials
      username: ${{ secrets.EMAIL_USERNAME }}
      password: ${{ secrets.EMAIL_PASSWORD }}
      # email subject
      subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
      # email body as text
      body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
      # comma-separated string, send email to
      to: darrshanaravind13897@gmail.com
      # from email name
      from: Darshan
