name: trigger inference

on:
  workflow_dispatch:

jobs:
  triggerinferencejob:
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2
      
  job2:
    if: always()
    needs: triggerinferencejob
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2
    - name: somestep
      run: echo ${{ job.status }}
      
  job3:
    if: always()
    needs: job2
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2
    - name: somestep
      run: echo ${{ job.status }}          
